# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestRegisterPlante():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testRegisterPlante(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1920, 1040)
    self.driver.find_element(By.CSS_SELECTOR, ".circle").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".circle")

    self.driver.find_element(By.LINK_TEXT, "Se connecter").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "form2Example17").click()
    self.driver.find_element(By.ID, "form2Example17").send_keys("remi@remi.fr")
    self.driver.find_element(By.ID, "form2Example27").click()
    self.driver.find_element(By.ID, "form2Example27").send_keys("T@st96745")
    self.driver.find_element(By.ID, "logButton").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "registerPlante").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "inputname").click()
    self.driver.find_element(By.ID, "inputname").send_keys("Testrosa")
    self.driver.find_element(By.ID, "number").click()
    self.driver.find_element(By.ID, "number").send_keys("12")
    self.driver.find_element(By.ID, "road").click()
    self.driver.find_element(By.ID, "road").send_keys("rue Antoine Vivaux")
    self.driver.find_element(By.ID, "town").click()
    self.driver.find_element(By.ID, "town").send_keys("Cuges-les-pins")
    self.driver.find_element(By.ID, "code").click()
    self.driver.find_element(By.ID, "code").send_keys("13780")
    openPhoto = self.driver.find_element(By.ID, "openPhoto")
    self.driver.execute_script("arguments[0].click();", openPhoto)
    time.sleep(2)
    self.driver.find_element(By.ID, "StartCamera").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "TakePhoto").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "UploadPhoto").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "uploadPlante").click()
  
