# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from database import *

class TestTestUserRegister():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')

    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
    self.connection = MSQL
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testUserRegister(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1014, 1040)
    self.driver.find_element(By.CSS_SELECTOR, ".circle").click()
    self.driver.find_element(By.LINK_TEXT, "S\'inscrire").click()

    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Gaetan")
    self.driver.find_element(By.ID, "firstname").send_keys("Tiberghien")
    self.driver.find_element(By.ID, "phone").send_keys("0611021158")
    self.driver.find_element(By.ID, "email").send_keys("gaetan@yamel.fr")
    self.driver.find_element(By.ID, "password").send_keys("Lyr&tre741")
    self.driver.find_element(By.ID, "confirmPassword").send_keys("Lyr&tre741")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-warning:nth-child(2)").click()

    time.sleep(2)

    with self.connection.cursor() as cursor:
      query = "select name from Person where name = 'Gaetan';"
      cursor.execute(query)
      row = cursor.fetchone()
      if row[0] == "Gaetan":
        assert True
      else:
        assert False
