version: '3'

services:
  mysql-db:
    build:
      context: ./MSPR-BDD-B3-MySQL/.
      dockerfile: Dockerfile
    restart: always

  python-api:
    depends_on:
      - mysql-db
    build:
      context: ./MSPR-BDD-B3-Backend/.
      dockerfile: Dockerfile
    restart: always

  react-web:
    depends_on:
      - python-api
    build:
      context: ./MSPR-BDD-B3-WebApp/.
      dockerfile: Dockerfile
    restart: always