version: '3'

services:
  mysql-db-compose:
    build:
      context: ./MSPR-BDD-B3-MySQL/.
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      # MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    restart: always
    ports:
      - '3306:3306'
      - '33060:33060'
    networks:
      - my-network

  python-api-compose:
    depends_on:
      - mysql-db-compose
    build:
      context: ./MSPR-BDD-B3-Backend/.
      dockerfile: Dockerfile
    # environment:
    #   DB_HOST: @mysql-db-compose:3306
    restart: always
    ports:
      - '8005:8005'
    networks:
      - my-network

  react-web-compose:
    depends_on:
      - python-api-compose
    build:
      context: ./MSPR-BDD-B3-WebApp/front/.
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge