name: main branch CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set environment variables
      run: |
      
    - name: Deploy to Server via SSH action
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USER }}
        key: ${{ secrets.SSH_PEM }}
        port: 22 
        script: |



          # Stop all running Docker Containers
          # if [ "$(docker ps -a -q)" ]; then
          #   docker kill $(docker ps -a -q)
          #   docker rm $(docker ps -a -q)
          # fi
          cd MSPR-BDD-B3/
          git pull
          sudo docker compose up -d --build
        env:
          export SECRET="7e9356d97f7a42d61d9194f2c82f39f545620fb45fc95a34d92330f14d7869f3"
          export ALGORITHM="HS256"


          export HOST_LOCAL="172.19.0.4"
          export HOST_CONTAINER="mysql-db-compose"
          export USER_LOCAL="admin"
          export USER_CONTAINER="admin"
          export PASSWORD_LOCAL="admin"
          export PASSWORD_CONTAINER="admin"
          export DB_LOCAL="Arosaje_db"
          export DB_CONTAINER="Arosaje_db"
          export PORT_LOCAL="3306"
          export PORT_CONTAINER="3306"


  
  