name: main branch CI/CD

on:
  workflow_dispatch:
  push: #Instance à l'arret , changez l'ip pour pouvoir le relancer
    branches: [ "main" ]

env:
  SECRET: ${{ secrets.SECRET_KEY }}
  ALGORITHM: ${{ secrets.ALGORITHM }}
  HOST_CONTAINER: ${{ secrets.HOST_CONTAINER }}
  USER_LOCAL: ${{ secrets.USER_LOCAL }}
  USER_CONTAINER: ${{ secrets.USER_LOCAL }}
  PASSWORD_LOCAL: ${{ secrets.PASSWORD_LOCAL }}
  PASSWORD_CONTAINER: ${{ secrets.PASSWORD_CONTAINER }}
  DB_LOCAL: ${{ secrets.DB_LOCAL }}
  DB_CONTAINER: ${{ secrets.DB_CONTAINER }}
  PORT_CONTAINER: "3306"
  REACT_APP_API_URL: $ {{ secrets.HOST }}
  
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create .env file
      run: |
        cd MSPR-BDD-B3/MSPR-BDD-B3-Backend/back/src
        echo "SECRET=${{ secrets.SECRET_KEY }}" > .env
        echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> .env
        echo "HOST_CONTAINER=${{ secrets.HOST_CONTAINER }}" >> .env
        echo "USER_LOCAL=${{ secrets.USER_LOCAL }}" >> .env
        echo "USER_CONTAINER=${{ secrets.USER_CONTAINER }}" >> .env
        echo "PASSWORD_LOCAL=${{ secrets.PASSWORD_LOCAL }}" >> .env
        echo "PASSWORD_CONTAINER=${{ secrets.PASSWORD_CONTAINER }}" >> .env
        echo "DB_LOCAL=${{ secrets.DB_LOCAL }}" >> .env
        echo "DB_CONTAINER=${{ secrets.DB_CONTAINER }}" >> .env
        echo "PORT_CONTAINER=3306" >> .env
        echo "REACT_APP_API_URL=${{ secrets.HOST }}" >> .env
        
    - name: Deploy to Server via SSH action
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USER }}
        key: ${{ secrets.SSH_PEM }}

        port: 22 
        script: |
          # Stop all running Docker Containers and remove all cache
          docker system prune -a --volumes
          cd MSPR-BDD-B3/
          git pull
          sudo docker compose up -d --build
          echo "This is an environment variable: $HOST_LOCAL"
          echo "This is an environment variable: $SECRET"
          echo "This is an environment variable: $ALGORITHM"
          echo "REACT_APP_API_URL : $REACTURL"
          echo "This is an environment variable: $PORT_LOCAL"
          
          

