name: main branch CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    env:
      DB_USERS: ${{ secrets.DB_USERS }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      HOST_LOCAL: ${{ secrets.HOST_LOCAL }}
      HOST_CONTAINER: ${{ secrets.HOST_CONTAINER}}
      USER_LOCAL: ${{ secrets.USER_LOCAL}}
      USER_CONTAINER: ${{ secrets.USER_CONTAINER}}
      PASSWORD_LOCAL: ${{ secrets.PASSWORD_LOCAL}}
      PASSWORD_CONTAINER: ${{ secrets.PASSWORD_CONTAINER}}
      DB_LOCAL: ${{ secrets.DB_LOCAL}}
      DB_CONTAINER: ${{ secrets.DB_LOCAL}}
      PORT_LOCAL: ${{ secrets.PORT}}
      PORT_CONTAINER: ${{ secrets.PORT}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set environment variables
      run: |
        source ./MSPR-BDD-B3-Backend/back/src/.env
        envBackPath="./MSPR-BDD-B3-Backend/back/src/.env"
      
    - name: Deploy to Server via SSH action
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USER }}
        key: ${{ secrets.SSH_PEM }}
        port: 22 
        script: |
          # Stop all running Docker Containers
          # if [ "$(docker ps -a -q)" ]; then
          #   docker kill $(docker ps -a -q)
          #   docker rm $(docker ps -a -q)
          # fi
          cd MSPR-BDD-B3/
          git pull
          sudo docker compose up -d --build