name: main branch CI/CD

on:
  workflow_dispatch:
  push: #Instance à l'arret , changez l'ip pour pouvoir le relancer
    branches: [ "main" ]

env:
  ALGORITHM: "HS256"
  HOST_CONTAINER: "mysql-db-compose"
  USER_LOCAL: "admin"
  USER_CONTAINER: "admin"
  PASSWORD_LOCAL: "admin"
  PASSWORD_CONTAINER: "admin"
  DB_LOCAL: "Arosaje_db"
  DB_CONTAINER: "Arosaje_db"
  PORT_CONTAINER: "3306"
  
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to Server via SSH action
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USER }}
        key: ${{ secrets.SSH_PEM }}

        port: 22 
        script: |
          # Stop all running Docker Containers and remove all cache
          docker system prune -a --volumes
          cd MSPR-BDD-B3/
          git pull
          sudo docker compose up -d --build
          echo "This is an environment variable: $HOST_LOCAL"
          echo "This is an environment variable: $SECRET"
          echo "This is an environment variable: $ALGORITHM"
          echo "REACT_APP_API_URL : $REACTURL"
          echo "This is an environment variable: $PORT_LOCAL"
          
          

