name: Python Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
          path: MSPR-BDD-B3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pwd
          ls
          python -m pip install --upgrade pip
          pip install -r MSPR-BDD-B3/Backend/requirements.txt

      - name: Run tests file 1
        run: |
          pwd
          python MSPR-BDD-B3-BackEnd/Backend/src/test_takeLatinTupleGetUtf8List.py

      - name: Run tests file 2
        run: |
          python MSPR-BDD-B3/Tests/test_testLogin.py
