name: Python Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout my project

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r MSPR-BDD-B3-Backend/requirements.txt

      - name: Run Tests
        run: |
          cd ..
          pip install pytest
          pip install virtualenv
          python -m venv env
          source env/bin/activate
          cd MSPR-BDD-B3/MSPR-BDD-B3-Backend/back/src
          pytest

