name: selenium testing docker-compose

on:
  push:
    branches:
      - selenium
  pull_request:
    branches:
      - selenium

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: selenium

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build Docker stack
      run: |
        docker-compose build
        docker-compose up -d

    - name: Run Selenium tests
      run: |
        cd ./MSPR-BDD-B3-Tests
        # Install dependencies for your test project, e.g. Python and pip for Python projects
        sudo apt-get install -y python3 python3-pip
        # Install Selenium and other required packages
        pip install -r ./requirements.txt
        # Run your Selenium tests
        python3 -m pytest

    - name: Stop Docker Compose stack
      if: always()
      run: docker-compose down
